"""GitHub Actions entry point for Mantis.

Reads the PR event context, runs the regression detection pipeline,
posts results as a PR comment, and exits with the appropriate code.
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
load_dotenv()

from mantis.blast_radius import find_blast_radius
from mantis.diff_parser import parse_diff
from mantis.reporter import format_github_comment
from mantis.runner import run_tests
from mantis.test_generator import generate_tests, generate_probe_script
from mantis.differential import run_differential


def _read_event() -> dict:
    event_path = os.environ.get("GITHUB_EVENT_PATH", "")
    if not event_path or not Path(event_path).exists():
        _die("GITHUB_EVENT_PATH not set or file missing. Must run inside GitHub Actions.")
    with open(event_path) as f:
        return json.load(f)


def _die(msg: str) -> None:
    print(f"::error::{msg}")
    sys.exit(1)


def _log(msg: str) -> None:
    print(msg)


def _set_output(name: str, value: str) -> None:
    output_file = os.environ.get("GITHUB_OUTPUT", "")
    if output_file:
        with open(output_file, "a") as f:
            f.write(f"{name}={value}\n")


def _post_comment(repo_full_name: str, pr_number: int, body: str) -> None:
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        _log("No GITHUB_TOKEN -- skipping PR comment.")
        return

    import requests
    resp = requests.post(
        f"https://api.github.com/repos/{repo_full_name}/issues/{pr_number}/comments",
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
        },
        json={"body": body},
        timeout=30,
    )
    if resp.status_code == 201:
        _log(f"Posted comment: {resp.json().get('html_url', '')}")
    else:
        _log(f"::warning::Failed to post comment: {resp.status_code} {resp.text[:200]}")


def _format_differential_comment(
    diff_result, blast_radius, diff_obj, pr_title: str,
) -> str:
    """Format differential testing results as a markdown PR comment."""
    lines: list[str] = []
    lines.append("## 🦗 Mantis Regression Report (Differential)")
    lines.append("")

    if pr_title:
        lines.append(f"> **{pr_title}**")
        lines.append("")

    n_files = len(diff_result.changed_files)
    n_funcs = len(diff_result.changed_functions)
    n_blast = len(blast_radius)
    lines.append(
        f"**{n_files} file{'s' if n_files != 1 else ''} changed, "
        f"{n_funcs} function{'s' if n_funcs != 1 else ''} modified** · "
        f"**{n_blast} blast radius function{'s' if n_blast != 1 else ''}**"
    )
    lines.append("")

    new_crashes = [d for d in diff_obj.diffs if d.category == "new_crash"]
    behavioral = [d for d in diff_obj.diffs if d.category == "behavioral_change"]
    new_fixes = [d for d in diff_obj.diffs if d.category == "new_fix"]

    if new_crashes:
        lines.append("### 💥 New Crashes")
        for item in new_crashes:
            lines.append(f"- `{item.probe_name}` — {item.head_error or 'crashed'}")
        lines.append("")

    if behavioral:
        lines.append("### 🔄 Behavioral Changes")
        for item in behavioral:
            lines.append(f"- `{item.probe_name}`")
            if item.base_value and item.head_value:
                lines.append(f"  - Before: `{item.base_value[:100]}`")
                lines.append(f"  - After: `{item.head_value[:100]}`")
        lines.append("")

    if new_fixes:
        lines.append("### ✅ New Fixes")
        for item in new_fixes:
            lines.append(f"- `{item.probe_name}` — previously crashed, now works")
        lines.append("")

    regressions = len(new_crashes) + len(behavioral)
    if regressions > 0:
        lines.append(
            f"### ❌ Verdict: {regressions} "
            f"regression{'s' if regressions != 1 else ''} detected. "
            "Not safe to merge."
        )
    else:
        lines.append("### ✅ Verdict: No behavioral regressions detected. Safe to merge.")

    lines.append("")
    lines.append("---")
    lines.append("*Generated by [Mantis](https://github.com/waqquuu/Mantis) — regression detection for pull requests*")

    return "\n".join(lines)


def main() -> None:
    event = _read_event()

    pr = event.get("pull_request")
    if not pr:
        _die("This action only runs on pull_request events.")

    pr_number = pr["number"]
    pr_title = pr.get("title", "")
    base_sha = pr["base"]["sha"]
    head_sha = pr["head"]["sha"]
    repo_full_name = event["repository"]["full_name"]

    mode = os.environ.get("MANTIS_MODE", "both")
    depth = int(os.environ.get("MANTIS_DEPTH", "2"))
    timeout = int(os.environ.get("MANTIS_TIMEOUT", "120"))
    post_comment = os.environ.get("MANTIS_POST_COMMENT", "true").lower() == "true"

    repo_path = os.environ.get("GITHUB_WORKSPACE", ".")

    _log(f"Mantis analyzing PR #{pr_number}: {pr_title}")
    _log(f"  base={base_sha[:8]}  head={head_sha[:8]}  mode={mode}")

    # Step 1: Parse diff
    try:
        diff_result = parse_diff(repo_path, base=base_sha, head=head_sha)
    except RuntimeError as e:
        _die(f"Diff parsing failed: {e}")

    if not diff_result.changed_functions:
        _log("No Python function changes detected.")
        _set_output("result", "skip")
        sys.exit(0)

    _log(f"Changed functions: {len(diff_result.changed_functions)}")

    # Step 2: Blast radius
    blast_radius = find_blast_radius(
        diff_result.changed_functions, repo_path, max_depth=depth,
    )
    _log(f"Blast radius: {len(blast_radius)} connected functions")

    if not blast_radius:
        _log("No blast radius — changes don't affect other functions.")
        if post_comment:
            body = format_github_comment(diff_result, blast_radius, None, pr_title)
            _post_comment(repo_full_name, pr_number, body)
        _set_output("result", "pass")
        sys.exit(0)

    has_regressions = False

    # Step 3: Standard mode
    if mode in ("standard", "both"):
        _log("Running standard regression tests...")
        try:
            test_code = generate_tests(
                changed_functions=diff_result.changed_functions,
                blast_radius=blast_radius,
                raw_diff=diff_result.raw_diff,
                repo_path=repo_path,
            )
            run_result = run_tests(test_code, repo_path, timeout=timeout)

            _log(f"  {run_result.passed} passed, {run_result.failed} failed, {run_result.errors} errors")

            if run_result.failed > 0:
                has_regressions = True

            if post_comment:
                body = format_github_comment(diff_result, blast_radius, run_result, pr_title)
                _post_comment(repo_full_name, pr_number, body)

        except Exception as e:
            import traceback
            _log(f"::warning::Standard test generation/execution failed: {e}")
            _log(traceback.format_exc())

    # Step 4: Differential mode
    if mode in ("differential", "both"):
        _log("Running differential testing...")
        try:
            probe_code = generate_probe_script(
                changed_functions=diff_result.changed_functions,
                blast_radius=blast_radius,
                raw_diff=diff_result.raw_diff,
                repo_path=repo_path,
            )
            diff_obj = run_differential(
                probe_code=probe_code,
                repo_path=repo_path,
                base_ref=base_sha,
                head_ref=head_sha,
                timeout=timeout,
            )

            n_crashes = len([d for d in diff_obj.diffs if d.category == "new_crash"])
            n_behavioral = len([d for d in diff_obj.diffs if d.category == "behavioral_change"])
            _log(f"  {n_crashes} new crashes, {n_behavioral} behavioral changes")

            if diff_obj.regressions:
                has_regressions = True

            if post_comment:
                body = _format_differential_comment(
                    diff_result, blast_radius, diff_obj, pr_title,
                )
                _post_comment(repo_full_name, pr_number, body)

        except Exception as e:
            import traceback
            _log(f"::warning::Differential testing failed: {e}")
            _log(traceback.format_exc())

    # Step 5: Set result
    if has_regressions:
        _set_output("result", "fail")
        _log("❌ Regressions detected.")
        sys.exit(1)
    else:
        _set_output("result", "pass")
        _log("✅ No regressions detected.")
        sys.exit(0)


if __name__ == "__main__":
    main()
